run:
  tests: true
  build-tags:
    - bench
    - !bench

linters-settings:
  funlen:
    lines: 150
    statements: 80

issues:
  exclude-rules:
    # Исключаем авто-сгенерированный файл API из всех проверок
    - path: api/calendarapi\.go
      linters:
        - revive
        - lll
        - gofumpt
        - tagliatelle
        - unparam
        - empty-block
        - var-naming
        - stylecheck

    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - gocyclo
        - gosec
        - revive
    - path: internal/storage/memory/storage_test\.go
      linters:
        - errorlint
    - path: internal/logger/logger_test\.go
      linters:
        - revive

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - dupl
    - durationcheck
    - exhaustive
    - funlen
    - gci
    - gocognit
    - goconst
    - godot
    - gofmt
    - gofumpt
    - goheader
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - tagliatelle
    - thelper
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
