global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'calendar'
    static_configs:
      - targets: ['calendar:8888']
  - job_name: 'scheduler'
    static_configs:
      - targets: ['scheduler:9091']
  - job_name: 'storer'
    static_configs:
      - targets: ['storer:9093']
