logger:
  level: "info"

storage:
  type: "sql"

database:
  host: "localhost"
  port: 5432
  user: "calendar"
  password: "calendar"
  database: "calendar"

kafka:
  bootstrap_servers:
    - "localhost:9092"
  topic: "calendar_notifications"

scheduler:
  scan_interval: "1m"