logger:
  level: "info"

database:
  host: "postgres"
  port: 5432
  user: "calendar"
  password: "calendar"
  database: "calendar"

kafka:
  bootstrapServers:
    - "kafka:9090"
  topic: "calendar_notifications"

storer:
  kafkaTopic: "calendar_notifications"
